### ISSUE TITLE
extraction

### ISSUE THREAD

**Issue by a-rabin** [Cacodemon345/GloDecrypt#1]
What are the parameters of this program? How do I extract the assets from this program?

**Comment by Cacodemon345** [comment]
Specify the name of the directory you want to extract into as the 4th parameter, specifying the 3rd argument as 'extract'. Note that the program will extract the levels into the previous folder's 'level' subfolder of the directory the assets will be extracted into, so keep that in mind.

**Comment by a-rabin** [comment]
Can you show an command line example? It is not working for me here.

**Comment by Cacodemon345** [comment]
`.\GloDecrypt.exe pathtoball.glo pathtodecryptedball.glo extract pathtoballdirectory`

This should make it work. What error do you get by the way?

**Comment by a-rabin** [comment]
What does it mean by pathtodecryptedball.glo? do i have to do something extra?
and no errors, just i dont know how to use ths software.

**Comment by Cacodemon345** [comment]
It's a path to the resultant decrypted file (the one shipped with the game is naively encrypted).

**Comment by a-rabin** [comment]
so how do i decrypt the ball.glo file?

**Comment by Cacodemon345** [comment]
You don't have to do that; the utility will decrypt and write it into the pathtodecryptedball.glo file when extracting.

**Comment by a-rabin** [comment]
oh okay, i guess ill try it tomorrow morning. ill update you

**Comment by a-rabin** [comment]
okay it works now. thanks
